### ISSUE TITLE
【BE】API洗い出し

### ISSUE THREAD

**Issue by ysm0706glee** [qin-team-recipe/11-recipe-api#4]
figmaの左上から順番に見ていきました
- 検索？
- 注目のシェフ(直近3日間の獲得フォロワー数の上位10人)
もっとみるがあるからlimitが必要そう
- 話題のレシピ(直近3日間の獲得お気に入り数の上位10レシピ)
もっとみるがあるからlimitが必要そう
- シェフ一覧(あいうえお順)
- レシピ一覧
- シェフ詳細(シェフのレシピやリンクも)
- シェフフォロー
- レシピ詳細(作り方や材料も)
- レシピいいね
- まとめてお買い物に追加
- お買い物に追加
- フォローシェフ一覧(あいうえお順)
- レシピお気に入り一覧(追加順)
- マイレシピ作成
- マイレシピ下書き
- 買い物リストのじぶんメモ追加
- 買い物リストのじぶんメモ削除
- 買い物リスト一覧
- 買い物リストの材料購入したかどうか
- 買い物リストの移動(上下)
- 買い物リストに材料追加
- 買い物リストからレシピ削除

疑問に思った点
- グラタンと検索してシェフも出てくる
<img width="337" alt="Screenshot 2023-06-13 at 20 01 03" src="https://github.com/qin-team-recipe/11-recipe-api/assets/74037163/dbc8914e-d5f8-4694-9c5b-735ff10e2737">

**Comment by aguriken** [comment]
@ysm0706glee 
昨日ryutaroさんと確認しましたので、20(火)のMTGで内容の確認と分担出来ればと思います！
https://www.notion.so/0509e673ac284e0f8bfef85230d7249b?pvs=4#7497371b2e004f35a7a09f1be34c8456

**Comment by ryutaroda** [comment]
@ysm0706glee @aguriken 
こちらにリストでまとめてみました。slackのチャンネルにも「API一覧」としてリンクを追加しています。
6/20(火)のMTGで確認後こちらのissueをcloseしましょう！
https://github.com/qin-team-recipe/11-recipe-api/wiki/API%E4%B8%80%E8%A6%A7

一応notionにも追加しました。
https://www.notion.so/0509e673ac284e0f8bfef85230d7249b?pvs=4#70b872c1bb9b4c09ae468914e7b609e4
